### ISSUE TITLE
addon not compatible with Firefox 52

### ISSUE THREAD

**Issue by vbooka1** [t-tera/FormVisualizer#4]
Addon page says "Works with firefox 48.0 and later" but trying to install it from https://addons.mozilla.org/en-US/firefox/addon/formvisualizer/ gives an error "Installation aborted because the add-on appears to be corrupt."

I downloaded the .xpi file and tried to install it as a temporary addon at about:debugging#addons and got an error "There was an error during installation: Extension is invalid".
The file downloaded 100% correctly - I can unzip it and see sources inside, no files are corrupt, so it is an incompatibility with old Firefox and addon.

Is there any workaround?

P.S. config "xpinstall.signatures.required" is "false".

**Comment by vbooka1** [comment]
I have managed to fix it by editing manifest.json file - removed "commands" section entirely; changed "content_scripts" - "matches"; and added "applications" section. 
Here is a resulting manifest.json file: https://gist.github.com/vbooka1/2def4019273d2a9134e51186876b2e4b
please check

**Comment by vbooka1** [comment]
Sorry, it is not required to change the "matches", else addons stops working. So it is only needed to remove the "commands" section and add the "applications" section.

**Comment by vbooka1** [comment]
Still could not make it work... seems that extension messages do not come to the background script.

I've added a few alerts:
cs_main.js:

```
alert("DEBUG: begin sendmessage bg-open-node-edit");
            browser.runtime.sendMessage({
                command: 'form-visualizer.bg-open-node-edit',
                spanId: span.id,
                editArgs: JSON.parse(span.dataset.editArgs),
                tagName: tag,
                typeAttrVal: rnode.type,
                ndtype: span.ndtype
            }); 
alert("DEBUG: end sendmessage bg-open-node-edit");
```

bg_main.js:

```
browser.runtime.onMessage.addListener((msg, sender) => {
alert("DEBUG: bg: onmessage listener");
```

When I click on any form element (to edit the form) I see two alerts "begin sendmessage bg-open-node-edit" and "end sendmessage bg-open-node-edit" but not an alert "bg: onmessage listener", and edit form window does not appear.
But all functions inside browser.commands.onCommand.addListener work well - I can see DOM HTML source, can toggle form visualization. So onCommand listener works but onMessage listener does not work.

The addon debugger console throws an error "Could not establish connection. Receiving end does not exist." in cs_main.js on line 460 (my 2nd alert "end sendmessage bg-open-node-edit").

Unfortunately I do not know Javascript so can not debug further.

**Comment by t-tera** [comment]
Sorry for my late response.

Firefox 52 was released back in 2017. I guess some changes have been made to Firefox API since then.
I confirmed the extension works with latest version of Firefox. Can you use this extension with the latest version?

Thank you

**Comment by vbooka1** [comment]
I guess nobody uses Firefox 52 anymore. Issue "resolved" by upgrading to a more recent ESR version.
